# .streamlit/secrets.toml
GITHUB_TOKEN = "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
DEV"
DATA_OWNER   = "StevRocket"              # or your org
DATA_REPO    = "private-data"
DATA_BRANCH  = "main"                  # optional; defaults to main
DATA_PREFIX  = "data"                  # folder inside the repo that holds CSVs
