# .streamlit/secrets.toml
GITHUB_TOKEN = "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"
DATA_OWNER   = "StevRocket"              # or your org
DATA_REPO    = "private-data"
DATA_BRANCH  = "main"                  # optional; defaults to main
DATA_PREFIX  = "data"                  # folder inside the repo that holds CSVs
